export enum Language {
  PHP = 'php',
  PYTHON = 'python',
  C = 'c',
  C_CPP = 'c_cpp',
  CSHARP = 'csharp',
  KOTLIN = 'kotlin',
  GOLANG = 'golang',
  R = 'r',
  JAVA = 'java',
  TYPESCRIPT = 'typescript',
  NODEJS = 'nodejs',
  RUBY = 'ruby',
  PERL = 'perl',
  SWIFT = 'swift',
  FORTRAN = 'fortran',
  BASH = 'bash',
}

export const LanguageDisplayNames: { [key in Language]: string } = {
  [Language.PHP]: 'PHP',
  [Language.PYTHON]: 'Python',
  [Language.C]: 'C',
  [Language.C_CPP]: 'C/C++',
  [Language.CSHARP]: 'C#',
  [Language.KOTLIN]: 'Kotlin',
  [Language.GOLANG]: 'Go',
  [Language.R]: 'R',
  [Language.JAVA]: 'Java',
  [Language.TYPESCRIPT]: 'TypeScript',
  [Language.NODEJS]: 'Node.js',
  [Language.RUBY]: 'Ruby',
  [Language.PERL]: 'Perl',
  [Language.SWIFT]: 'Swift',
  [Language.FORTRAN]: 'Fortran',
  [Language.BASH]: 'Bash',
};
