export enum Language {
  PHP = 'php',
  PYTHON = 'python',
  C = 'c',
  C_CPP = 'c_cpp',
  CSHARP = 'csharp',
  KOTLIN = 'kotlin',
  GOLANG = 'golang',
  R = 'r',
  JAVA = 'java',
  TYPESCRIPT = 'typescript',
  NODEJS = 'nodejs',
  RUBY = 'ruby',
  PERL = 'perl',
  SWIFT = 'swift',
  FORTRAN = 'fortran',
  BASH = 'bash',
}
