export enum Language {
  PHP = 'PHP',
  PYTHON = 'Python',
  C = 'C',
  C_CPP = 'C/C++',
  CSHARP = 'C#',
  KOTLIN = 'Kotlin',
  GOLANG = 'Go',
  R = 'R',
  JAVA = 'Java',
  TYPESCRIPT = 'TypeScript',
  NODEJS = 'Node.js',
  RUBY = 'Ruby',
  PERL = 'Perl',
  SWIFT = 'Swift',
  FORTRAN = 'Fortran',
  BASH = 'Bash',
}
